services:
  - type: pserv
    name: pwp67-db
    env: docker
    plan: free
    databases:
      - name: devdb
        user: ups

  - type: web
    name: pwp67-api
    env: java
    plan: free
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/springboot-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: pwp67-db
          property: connectionString
