spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: ups
    password: ups123
  jpa:
    # Muestra las consultas SQL en la consola
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Organiza el SQL para que sea legible
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración de niveles de log para ver los parámetros (? -> valor)
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

server:
  port: 8080